import React from 'react';
import { Image as ImageIcon, Table2, FileText, BarChart2 } from 'lucide-react';
import { useApp } from '../../../context/AppContext';
import { seleneApi } from '../../../services/api';

export const ExportsView: React.FC = () => {
  const { addLog, addToast, results, isComplete } = useApp();

  const jobId = results.jobId;
  const isReal = isComplete && jobId && !jobId.startsWith('demo_');

  const handleDownload = (productPath: string | undefined, filename: string) => {
    if (isReal && productPath) {
      // Real backend download — open the static-files URL served by FastAPI
      const url = seleneApi.productUrl(productPath);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.target = '_blank';
      a.click();
      addLog(`Downloading ${filename} from backend…`, 'success');
      addToast(`Downloading ${filename} from the server.`, 'success', 'Download Started');
    } else {
      // Demo fallback — generate a placeholder blob
      let content = '';
      let mimeType = 'text/plain';

      if (filename.endsWith('.csv')) {
        content =
          'source_x,source_y,reference_x,reference_y,inlier,confidence\n120.2,88.4,121.0,88.9,1,0.98\n240.5,156.2,241.1,155.7,1,0.96\n';
        mimeType = 'text/csv';
      } else if (filename.endsWith('.pdf')) {
        content =
          'SELENE-MATCH registration report\nRMSE: 0.68 px\nInlier Ratio: 87.6%\nCE90: 0.91 px\nNNI: 0.84\nGrid Coverage: 81%\n';
        mimeType = 'application/pdf';
      } else {
        content =
          'SELENE-MATCH simulated registered GeoTIFF placeholder. Upload real images and run the pipeline for live raster export.';
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      addLog(`Prepared demo download: ${filename}`, 'success');
      addToast(`${filename} (demo placeholder) downloaded.`, 'info', 'Demo Download');
    }
  };

  const exports = [
    {
      icon: <ImageIcon className="w-5 h-5 text-brand-400" />,
      borderColor: 'rgba(111,246,255,0.25)',
      bgColor: 'rgba(57,168,255,0.07)',
      filename: 'registered.tif',
      label: '↓ DOWNLOAD GEOTIFF',
      description: 'Registered GeoTIFF / final raster product.',
      productPath: isReal ? `/products/${jobId}/registered.tif` : undefined,
    },
    {
      icon: <Table2 className="w-5 h-5 text-success" />,
      borderColor: 'rgba(62,230,160,0.25)',
      bgColor: 'rgba(62,230,160,0.06)',
      filename: 'matches.csv',
      label: '↓ DOWNLOAD CSV',
      description: 'Correspondence and GCP records.',
      productPath: isReal ? `/products/${jobId}/matches.csv` : undefined,
    },
    {
      icon: <FileText className="w-5 h-5 text-warning" />,
      borderColor: 'rgba(255,182,92,0.25)',
      bgColor: 'rgba(255,182,92,0.06)',
      filename: 'registration_report.pdf',
      label: '↓ DOWNLOAD REPORT',
      description: 'One-page summary with metadata, metrics and visual proof.',
      productPath: isReal ? `/products/${jobId}/registration_report.pdf` : undefined,
    },
    {
      icon: <BarChart2 className="w-5 h-5 text-warning" />,
      borderColor: 'rgba(255,182,92,0.2)',
      bgColor: 'rgba(255,182,92,0.05)',
      filename: 'plot_checkerboard.png',
      label: '↓ CHECKERBOARD',
      description: 'Checkerboard overlay verification plot.',
      productPath: isReal ? `/products/${jobId}/plot_checkerboard.png` : undefined,
    },
  ];

  return (
    <section id="view-exports" className="view-section active">
      <div className="mb-5 flex items-center gap-3 flex-wrap">
        <div className="screen-title">Exports</div>
        {isReal ? (
          <span className="badge text-success" style={{ borderColor: 'rgba(62,230,160,0.3)' }}>
            LIVE · JOB {jobId}
          </span>
        ) : (
          <span className="badge text-warning" style={{ borderColor: 'rgba(255,182,92,0.3)' }}>
            DEMO MODE
          </span>
        )}
        <div className="screen-subtitle w-full">
          Download the tangible products generated by a registration job.
          {!isReal && (
            <span className="ml-2 text-warning">
              Run the pipeline with real images to download live outputs.
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
        {exports.map((exp) => (
          <div key={exp.filename} className="card bracket p-5 group">
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center mb-4 border"
              style={{ borderColor: exp.borderColor, background: exp.bgColor }}
            >
              {exp.icon}
            </div>
            <h3 className="text-white font-mono text-[12.5px] tracking-wide">{exp.filename}</h3>
            <p className="text-[11px] text-slate-500 mt-1.5 leading-relaxed">{exp.description}</p>
            <button
              onClick={() => handleDownload(exp.productPath, exp.filename)}
              className="btn-secondary w-full mt-5 py-2.5 rounded-lg text-[10px] tracking-[0.1em] font-mono"
            >
              {exp.label}
            </button>
          </div>
        ))}
      </div>

      <div className="card p-5 mt-5">
        <h3 className="text-[13px] font-semibold text-white tracking-wide">RUN PACKAGE</h3>
        <div className="term mt-3 p-4 font-mono text-[10px] text-slate-400 leading-[1.9]">
          <div className="text-brand-300">products/{isReal ? jobId : 'job_xxxxxxxx'}/</div>
          <div>├── registered.tif</div>
          <div>├── matches.csv</div>
          <div>├── plot_checkerboard.png</div>
          <div>├── plot_quiver.png</div>
          <div>├── plot_coverage.png</div>
          <div>└── registration_report.pdf</div>
        </div>
      </div>
    </section>
  );
};
